/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.alanproyect;

import javax.swing.DefaultListModel;

/**
 *
 * @author vidan
 */
public class Frm_Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frm_Principal.class.getName());
    DefaultListModel<String> modelo = new DefaultListModel<>();
    /**
     * Creates new form Frm_Principal
     */
    public Frm_Principal() {
        initComponents();
        jList1.setModel(modelo);
        this.setLocationRelativeTo(null);
        
        // Ocultamos el panel de los resultados al iniciar

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        TxtBx_IPRed = new java.awt.TextField();
        panelGroup_SeleccionarTipo = new java.awt.Panel();
        RdBtn_Subred = new javax.swing.JRadioButton();
        RdBtn_Host = new javax.swing.JRadioButton();
        label3 = new java.awt.Label();
        Btn_Calcular = new javax.swing.JButton();
        Panel_Resultados = new java.awt.Panel();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        Lbl_ResulPracSubred = new java.awt.Label();
        Lbl_ResulTeoriSubred = new java.awt.Label();
        Lbl_ResulTeoriHost = new java.awt.Label();
        Lbl_ResulPracHost = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        label10 = new java.awt.Label();
        TxtBx_Cantidad = new java.awt.TextField();
        Lbl_NuevaMask = new java.awt.Label();
        Lbl_Clase = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Subneteo Program");
        setResizable(false);

        label1.setFont(new java.awt.Font("Cascadia Code", 1, 36)); // NOI18N
        label1.setText("SUBNETEO");

        label2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label2.setText("IP de RED: ");

        TxtBx_IPRed.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtBx_IPRed.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        TxtBx_IPRed.addActionListener(this::TxtBx_IPRedActionPerformed);

        panelGroup_SeleccionarTipo.setBackground(new java.awt.Color(204, 204, 204));

        buttonGroup1.add(RdBtn_Subred);
        RdBtn_Subred.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RdBtn_Subred.setSelected(true);
        RdBtn_Subred.setText("Subredes");

        buttonGroup1.add(RdBtn_Host);
        RdBtn_Host.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RdBtn_Host.setText("Host * Subred");
        RdBtn_Host.setToolTipText("");

        label3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label3.setText("SELECCIONE:");

        javax.swing.GroupLayout panelGroup_SeleccionarTipoLayout = new javax.swing.GroupLayout(panelGroup_SeleccionarTipo);
        panelGroup_SeleccionarTipo.setLayout(panelGroup_SeleccionarTipoLayout);
        panelGroup_SeleccionarTipoLayout.setHorizontalGroup(
            panelGroup_SeleccionarTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGroup_SeleccionarTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RdBtn_Subred)
                .addGap(18, 18, 18)
                .addComponent(RdBtn_Host)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(panelGroup_SeleccionarTipoLayout.createSequentialGroup()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelGroup_SeleccionarTipoLayout.setVerticalGroup(
            panelGroup_SeleccionarTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGroup_SeleccionarTipoLayout.createSequentialGroup()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGroup_SeleccionarTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdBtn_Subred)
                    .addComponent(RdBtn_Host))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        RdBtn_Subred.getAccessibleContext().setAccessibleDescription("");

        Btn_Calcular.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Btn_Calcular.setText("Calcular");
        Btn_Calcular.addActionListener(this::Btn_CalcularActionPerformed);

        Panel_Resultados.setBackground(new java.awt.Color(219, 219, 249));

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setText("Teoricos: ");

        label5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label5.setText("#Host * Subred");

        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setText("Subredes:");

        label7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label7.setText("Practicos:");

        label8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label8.setText("Teoricos: ");

        label9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label9.setText("Practicos:");

        Lbl_ResulPracSubred.setText("Resultado");

        Lbl_ResulTeoriSubred.setText("Resultado");

        Lbl_ResulTeoriHost.setText("Resultado");

        Lbl_ResulPracHost.setText("Resultado");

        jList1.setBackground(new java.awt.Color(219, 219, 249));
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout Panel_ResultadosLayout = new javax.swing.GroupLayout(Panel_Resultados);
        Panel_Resultados.setLayout(Panel_ResultadosLayout);
        Panel_ResultadosLayout.setHorizontalGroup(
            Panel_ResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ResultadosLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(Panel_ResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_ResultadosLayout.createSequentialGroup()
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_ResulPracSubred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_ResultadosLayout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_ResulTeoriSubred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                .addGroup(Panel_ResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_ResultadosLayout.createSequentialGroup()
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_ResulPracHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_ResultadosLayout.createSequentialGroup()
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lbl_ResulTeoriHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(117, 117, 117))
            .addGroup(Panel_ResultadosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_ResultadosLayout.setVerticalGroup(
            Panel_ResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ResultadosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Panel_ResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Panel_ResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_ResultadosLayout.createSequentialGroup()
                        .addGroup(Panel_ResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_ResulTeoriSubred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(Panel_ResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_ResulPracSubred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_ResultadosLayout.createSequentialGroup()
                        .addGroup(Panel_ResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_ResulTeoriHost, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(Panel_ResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_ResulPracHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Lbl_ResulPracSubred.getAccessibleContext().setAccessibleDescription("");

        label10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label10.setText("Cantidad:");

        TxtBx_Cantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtBx_Cantidad.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        TxtBx_Cantidad.addActionListener(this::TxtBx_CantidadActionPerformed);

        Lbl_NuevaMask.setFont(new java.awt.Font("Cascadia Code", 1, 36)); // NOI18N
        Lbl_NuevaMask.setMaximumSize(new java.awt.Dimension(30000, 30000));
        Lbl_NuevaMask.setPreferredSize(new java.awt.Dimension(200, 40));
        Lbl_NuevaMask.setText("NuevaMask:");

        Lbl_Clase.setFont(new java.awt.Font("Cascadia Code", 1, 36)); // NOI18N
        Lbl_Clase.setText("CLASE:");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(Panel_Resultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(Lbl_Clase, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(TxtBx_IPRed, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TxtBx_Cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(panelGroup_SeleccionarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)
                                .addComponent(Btn_Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(Lbl_NuevaMask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Clase, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtBx_IPRed, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(panelGroup_SeleccionarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtBx_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(Lbl_NuevaMask, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(Btn_Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(Panel_Resultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        Lbl_NuevaMask.getAccessibleContext().setAccessibleName("NuevaMask:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBx_IPRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBx_IPRedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBx_IPRedActionPerformed

    private void TxtBx_CantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBx_CantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBx_CantidadActionPerformed
public void calcularRangos(String ip, int salto) {

    modelo.clear();

    String[] partes = ip.split("\\.");

    int o1 = Integer.parseInt(partes[0]);
    int o2 = Integer.parseInt(partes[1]);
    int o3 = Integer.parseInt(partes[2]);
    int o4 = Integer.parseInt(partes[3]);

    int total = 256 / salto;

    for (int i = 0; i < total; i++) {

        if (i < 3 || i >= total - 3) {

            int red = i * salto;
            int broadcast = red + salto - 1;

            String rango = "";

            if (o1 >= 1 && o1 <= 127) { // Clase A
                rango = o1 + "." + red + ".0.0 - " +
                        o1 + "." + broadcast + ".255.255";
            }
            else if (o1 >= 128 && o1 <= 191) { // Clase B
                rango = o1 + "." + o2 + "." + red + ".0 - " +
                        o1 + "." + o2 + "." + broadcast + ".255";
            }
            else { // Clase C
                rango = o1 + "." + o2 + "." + o3 + "." + red +
                        " - " +
                        o1 + "." + o2 + "." + o3 + "." + broadcast;
            }

            modelo.addElement(rango);
        }

        if (i == 3) {
            modelo.addElement("...");
        }
    }
}

    private void Btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CalcularActionPerformed
// Validación para que no truene si dejan algo vacío
        if(TxtBx_IPRed.getText().trim().isEmpty() || TxtBx_Cantidad.getText().trim().isEmpty()) {
            // Si están vacíos, lanzamos una alerta y el "return" cancela el cálculo para que el programa no truene.
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llena los campos de IP y Cantidad antes de calcular.");
            return; 
        }

        try {
            // Sacamos el texto que escribió el usuario y lo guardamos en variables.
            String ipIngresada = TxtBx_IPRed.getText().trim();
            // Convertimos el texto de la cantidad a un número entero 
            int cantidad = Integer.parseInt(TxtBx_Cantidad.getText().trim()); 
            // Vemos si el botoncito de "Subredes" está encendido (true) o apagado (false)
            boolean esSubred = RdBtn_Subred.isSelected();

            // Llamamos a la clase y le pasamos los datos que recolectamos.
            CalculadoraSubneteo miCalculo = new CalculadoraSubneteo(ipIngresada, cantidad, esSubred);
            miCalculo.calcular(); //Mandamos los datos que recolectamos para que haga los calculos :v

            //Le pedimos los resultados al objeto (usando los Get...) y los pegamos en los Labels.
            Lbl_ResulTeoriSubred.setText(String.valueOf(miCalculo.getSubredesTeoricas()));
            Lbl_ResulPracSubred.setText(String.valueOf(miCalculo.getSubredesPracticas()));
            Lbl_ResulTeoriHost.setText(String.valueOf(miCalculo.getHostsTeoricos()));
            Lbl_ResulPracHost.setText(String.valueOf(miCalculo.getHostsPracticos()));
            Lbl_Clase.setText("CLASE: " + miCalculo.getClaseRed());
            Lbl_NuevaMask.setText("Nueva Mask: " + miCalculo.getMascaraDecimal());
            
            
            int salto = miCalculo.getSalto(); 
            calcularRangos(ipIngresada, salto);


        } catch (Exception e) {
            // Si el usuario mete letras en lugar de números en la cantidad, el programa no se "crashea", sino que entra aquí y lanza error.
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Revisa que la IP tenga buen formato y la cantidad sea un número.");
        }
    }//GEN-LAST:event_Btn_CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Frm_Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Calcular;
    private java.awt.Label Lbl_Clase;
    private java.awt.Label Lbl_NuevaMask;
    private java.awt.Label Lbl_ResulPracHost;
    private java.awt.Label Lbl_ResulPracSubred;
    private java.awt.Label Lbl_ResulTeoriHost;
    private java.awt.Label Lbl_ResulTeoriSubred;
    private java.awt.Panel Panel_Resultados;
    private javax.swing.JRadioButton RdBtn_Host;
    private javax.swing.JRadioButton RdBtn_Subred;
    private java.awt.TextField TxtBx_Cantidad;
    private java.awt.TextField TxtBx_IPRed;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Panel panel1;
    private java.awt.Panel panelGroup_SeleccionarTipo;
    // End of variables declaration//GEN-END:variables
}
